Repository Azure/autorest.typescript, pull requests merged in 2018-11, with the labels that each got.

#359 Add deprecated method support
  src/DSL/TSBuilder.cs
  src/DSL/TSDocumentationComment.cs
  src/vanilla/Model/MethodTS.cs
  test/multiapi/packages/multiapi-test-2018-02-01/package-lock.json
  test/multiapi/packages/multiapi-test/package-lock.json
  unittests/DSL/TSDocumentationCommentTests.cs
  unittests/Models.cs
Labels: Started-Sprint-126, Unplanned-Sprint-126, in progress

#361 Trying to fix the bundle-size script/check
  .scripts/bundlesize.ts
  .scripts/dependencies.ts
  .scripts/repository.ts
  README.md
  package.json
  src/vanilla/Model/CodeModelTS.cs
  test/azuremetadata/generated/Lro/package.json
  test/metadata/generated/BodyComplex/package.json
  test/multiapi/packages/multiapi-test-2017-10-01/package-lock.json
  test/multiapi/packages/multiapi-test-2017-10-01/package.json
  test/multiapi/packages/multiapi-test-2018-02-01/package-lock.json
  test/multiapi/packages/multiapi-test-2018-02-01/package.json
  test/multiapi/packages/multiapi-test/package-lock.json
  test/multiapi/packages/multiapi-test/package.json
  tsconfig.json
Labels: Started-Sprint-126, Unplanned-Sprint-126, in progress

#362 Change default package version to 0.1.0
  src/vanilla/GeneratorSettingsTS.cs
Labels: Planned-Sprint-126, Started-Sprint-126, in progress

#365 Update ms-rest-js
  README.md
  package.json
  src/vanilla/Model/CodeModelTS.cs
  test/azuremetadata/generated/Lro/package.json
  test/metadata/generated/BodyComplex/package.json
  test/multiapi/packages/multiapi-test-2017-10-01/package-lock.json
  test/multiapi/packages/multiapi-test-2017-10-01/package.json
  test/multiapi/packages/multiapi-test-2018-02-01/package-lock.json
  test/multiapi/packages/multiapi-test-2018-02-01/package.json
  test/multiapi/packages/multiapi-test/package-lock.json
  test/multiapi/packages/multiapi-test/package.json
Labels: in progress

#353 Add additional check for expading mappers for polymorphic operation specs
  src/vanilla/ClientModelExtensions.cs
  test/azure/generated/AzureCompositeModelClient/models/mappers.ts
  test/metadata/generated/BodyComplex/lib/models/mappers.ts
  test/vanilla/complexTypesTests.ts
  test/vanilla/generated/BodyComplex/models/mappers.ts
Labels: in progress

#371 Only include .ts files in generated tsconfig include property
  src/vanilla/Templates/TsConfig.cshtml
  test/azuremetadata/generated/Lro/tsconfig.json
  test/metadata/generated/BodyComplex/tsconfig.json
  test/multiapi/packages/multiapi-test-2017-10-01/tsconfig.json
  test/multiapi/packages/multiapi-test-2018-02-01/tsconfig.json
  test/multiapi/packages/multiapi-test/tsconfig.json
Labels: Started-Sprint-126, Unplanned-Sprint-126, in progress

#373 Remove -preview suffix from generated package versions
  src/vanilla/GeneratorSettingsTS.cs
Labels: Started-Sprint-126, Unplanned-Sprint-126, in progress

#377 Add @azure prefix to the generated README files
  src/vanilla/Model/CodeModelTS.cs
  test/azuremetadata/generated/Lro/README.md
  test/metadata/generated/BodyComplex/README.md
  test/multiapi/packages/multiapi-test-2017-10-01/README.md
  test/multiapi/packages/multiapi-test-2018-02-01/README.md
  test/multiapi/packages/multiapi-test/README.md
Labels: Unplanned-Sprint-127, in progress

#375 Add Azure Pipelines configuration
  azure-pipelines.yml
  package.json
  test/vanilla/complexTypesTests.ts
Labels: Unplanned-Sprint-127, in progress

#385 Add sourcemaps plugin to generated rollup configuration
  src/DSL/JSBuilder.cs
  src/DSL/JSDocumentationComment.cs
  src/DSL/JSObject.cs
  src/vanilla/CodeGeneratorTS.cs
  src/vanilla/Model/CodeModelTS.cs
  src/vanilla/Templates/PackageJson.cshtml
  src/vanilla/Templates/RollupConfig.cshtml
  test/azuremetadata/generated/Lro/package.json
  test/azuremetadata/generated/Lro/rollup.config.js
  test/metadata/generated/BodyComplex/package.json
  test/metadata/generated/BodyComplex/rollup.config.js
  test/multiapi/packages/multiapi-test-2017-10-01/package-lock.json
  test/multiapi/packages/multiapi-test-2017-10-01/package.json
  test/multiapi/packages/multiapi-test-2017-10-01/rollup.config.js
  test/multiapi/packages/multiapi-test-2018-02-01/package-lock.json
  test/multiapi/packages/multiapi-test-2018-02-01/package.json
  test/multiapi/packages/multiapi-test-2018-02-01/rollup.config.js
  test/multiapi/packages/multiapi-test/package-lock.json
  test/multiapi/packages/multiapi-test/package.json
  test/multiapi/packages/multiapi-test/rollup.config.js
Labels: Planned-Sprint-127, Started-Sprint-127, in progress

#390 Remove previous publishing strategy and update version to 2.1.0
  .gulp/gulpfile.iced
  .gulp/publishing.iced
  package.json
Labels: Started-Sprint-127, Unplanned-Sprint-127, in progress
