Repository Azure/autorest.typescript, pull requests merged in 2018-10, with the labels that each got.

#321 Collect property types within an error body type
  src/vanilla/Model/MethodGroupTS.cs
Labels: in progress

#323 Fix local, preview, and latest scripts
  .scripts/dependencies.ts
  .scripts/repository.ts
  README.md
  package.json
  src/vanilla/Model/CodeModelTS.cs
  test/azuremetadata/generated/Lro/package.json
  test/metadata/generated/BodyComplex/package.json
  test/multiapi/packages/multiapi-test-2017-10-01/package-lock.json
  test/multiapi/packages/multiapi-test-2017-10-01/package.json
  test/multiapi/packages/multiapi-test-2018-02-01/package-lock.json
  test/multiapi/packages/multiapi-test-2018-02-01/package.json
  test/multiapi/packages/multiapi-test/package-lock.json
  test/multiapi/packages/multiapi-test/package.json
Labels: in progress

#322 Only add one contentType property
  src/vanilla/Model/MethodTS.cs
  unittests/AssertEx.cs
  unittests/DSL/TSBuilderTests.cs
  unittests/vanilla/Model/MethodTSTests.cs
Labels: in progress

#330 Exclude CloudErrorBody from OperationModelNames
  src/vanilla/Model/MethodGroupTS.cs
  unittests/AssertEx.cs
  unittests/Models.cs
  unittests/vanilla/Model/CodeModelTSTests.cs
  unittests/vanilla/Model/MethodGroupTSTests.cs
  unittests/vanilla/Model/MethodTSTests.cs
Labels: Started-Sprint-125, Unplanned-Sprint-125

#324 Rollup
  README.md
  package.json
  src/azure/Model/CodeModelTSa.cs
  src/azure/Templates/AzureReadmeTemplate.cshtml
  src/vanilla/CodeGeneratorTS.cs
  src/vanilla/GeneratorSettingsTS.cs
  src/vanilla/Model/CodeModelTS.cs
  src/vanilla/Templates/PackageJson.cshtml
  src/vanilla/Templates/ReadmeTemplate.cshtml
  src/vanilla/Templates/RollupConfig.cshtml
  src/vanilla/Templates/TsConfig.cshtml
  src/vanilla/Templates/TsConfigWebpack.cshtml
  src/vanilla/Templates/WebpackConfig.cshtml
  test/azuremetadata/generated/Lro/README.md
  test/azuremetadata/generated/Lro/package.json
  test/azuremetadata/generated/Lro/rollup.config.js
  test/azuremetadata/generated/Lro/tsconfig.esm.json
  test/azuremetadata/generated/Lro/tsconfig.json
  test/azuremetadata/generated/Lro/webpack.config.js
  test/metadata/generated/BodyComplex/README.md
  test/metadata/generated/BodyComplex/package.json
  test/metadata/generated/BodyComplex/rollup.config.js
  test/metadata/generated/BodyComplex/tsconfig.esm.json
  test/metadata/generated/BodyComplex/tsconfig.json
  test/metadata/generated/BodyComplex/webpack.config.js
  test/multiapi/multiapiTests.ts
  test/multiapi/packages/multiapi-test-2017-10-01/README.md
  test/multiapi/packages/multiapi-test-2017-10-01/package-lock.json
  test/multiapi/packages/multiapi-test-2017-10-01/package.json
  test/multiapi/packages/multiapi-test-2017-10-01/rollup.config.js
  test/multiapi/packages/multiapi-test-2017-10-01/tsconfig.esm.json
  test/multiapi/packages/multiapi-test-2017-10-01/tsconfig.json
  test/multiapi/packages/multiapi-test-2017-10-01/webpack.config.js
  test/multiapi/packages/multiapi-test-2018-02-01/README.md
  test/multiapi/packages/multiapi-test-2018-02-01/package-lock.json
  test/multiapi/packages/multiapi-test-2018-02-01/package.json
  test/multiapi/packages/multiapi-test-2018-02-01/rollup.config.js
  test/multiapi/packages/multiapi-test-2018-02-01/tsconfig.esm.json
  test/multiapi/packages/multiapi-test-2018-02-01/tsconfig.json
  test/multiapi/packages/multiapi-test-2018-02-01/webpack.config.js
  test/multiapi/packages/multiapi-test/README.md
  test/multiapi/packages/multiapi-test/package-lock.json
  test/multiapi/packages/multiapi-test/package.json
  test/multiapi/packages/multiapi-test/rollup.config.js
  test/multiapi/packages/multiapi-test/tsconfig.esm.json
  test/multiapi/packages/multiapi-test/tsconfig.json
  test/multiapi/packages/multiapi-test/webpack.config.js
Labels: in progress

#332 Update scripts to use non-greedy regular expressions and to use caret…
  .scripts/dependencies.ts
  README.md
  package.json
  src/azure/Model/CodeModelTSa.cs
  src/vanilla/Model/CodeModelTS.cs
  test/azuremetadata/generated/Lro/package.json
  test/metadata/generated/BodyComplex/package.json
  test/multiapi/packages/multiapi-test-2017-10-01/package-lock.json
  test/multiapi/packages/multiapi-test-2017-10-01/package.json
  test/multiapi/packages/multiapi-test-2018-02-01/package-lock.json
  test/multiapi/packages/multiapi-test-2018-02-01/package.json
  test/multiapi/packages/multiapi-test/package-lock.json
  test/multiapi/packages/multiapi-test/package.json
Labels: Planned-Sprint-125, Started-Sprint-125, in progress

#335 Add support for xmlPrefixes in mappers
  README.md
  package.json
  src/azure/Model/CodeModelTSa.cs
  src/vanilla/ClientModelExtensions.cs
  src/vanilla/Model/CodeModelTS.cs
  test/azuremetadata/generated/Lro/package.json
  test/metadata/generated/BodyComplex/package.json
  test/multiapi/packages/multiapi-test-2017-10-01/package-lock.json
  test/multiapi/packages/multiapi-test-2017-10-01/package.json
  test/multiapi/packages/multiapi-test-2018-02-01/package-lock.json
  test/multiapi/packages/multiapi-test-2018-02-01/package.json
  test/multiapi/packages/multiapi-test/package-lock.json
  test/multiapi/packages/multiapi-test/package.json
  unittests/Models.cs
  unittests/vanilla/ClientModelExtensionsTests.cs
Labels: Planned-Sprint-125, Started-Sprint-125, in progress

#336 Add xmlPrefix to xmlNames from properties
  src/vanilla/ClientModelExtensions.cs
  unittests/Models.cs
  unittests/vanilla/ClientModelExtensionsTests.cs
Labels: Planned-Sprint-125, Started-Sprint-125, in progress

#342 Fix generated samples
  src/DSL/TSBlock.cs
  src/DSL/TSBuilder.cs
  src/DSL/TSIfBlock.cs
  src/DSL/TSTryBlock.cs
  src/azure/Model/CodeModelTSa.cs
  src/azure/Templates/AzureReadmeTemplate.cshtml
  src/vanilla/Model/CodeModelTS.cs
  src/vanilla/Templates/ReadmeTemplate.cshtml
  test/azuremetadata/generated/Lro/README.md
  test/metadata/generated/BodyComplex/README.md
  test/multiapi/packages/multiapi-test-2017-10-01/README.md
  test/multiapi/packages/multiapi-test-2018-02-01/README.md
  test/multiapi/packages/multiapi-test/README.md
  unittests/DSL/TSBuilderTests.cs
  unittests/vanilla/Model/CodeModelTSTests.cs
Labels: Planned-Sprint-125, Started-Sprint-125, in progress

#347 Fix missing msRest import
  src/vanilla/Model/CodeModelTS.cs
Labels: in progress

#344 Use "files" from "packages.json" instead of ".npmignore".
  src/vanilla/CodeGeneratorTS.cs
  src/vanilla/Templates/NpmIgnore.cshtml
  src/vanilla/Templates/PackageJson.cshtml
  test/azuremetadata/generated/Lro/.npmignore
  test/azuremetadata/generated/Lro/README.md
  test/azuremetadata/generated/Lro/package.json
  test/metadata/generated/BodyComplex/.npmignore
  test/metadata/generated/BodyComplex/package.json
  test/multiapi/packages/multiapi-test-2017-10-01/.npmignore
  test/multiapi/packages/multiapi-test-2017-10-01/package.json
  test/multiapi/packages/multiapi-test-2018-02-01/.npmignore
  test/multiapi/packages/multiapi-test-2018-02-01/package.json
  test/multiapi/packages/multiapi-test/.npmignore
  test/multiapi/packages/multiapi-test/package.json
Labels: in progress

#345 Use "prepack" instead of "prepare".
  .gulp/gulpfile.iced
  src/vanilla/Templates/PackageJson.cshtml
  test/azuremetadata/generated/Lro/package.json
  test/metadata/generated/BodyComplex/package.json
  test/multiapi/package.json
  test/multiapi/packages/multiapi-test-2017-10-01/package-lock.json
  test/multiapi/packages/multiapi-test-2017-10-01/package.json
  test/multiapi/packages/multiapi-test-2018-02-01/package-lock.json
  test/multiapi/packages/multiapi-test-2018-02-01/package.json
  test/multiapi/packages/multiapi-test/package-lock.json
  test/multiapi/packages/multiapi-test/package.json
Labels: in progress

#349 Fix overriding properties from parent context class
  src/DSL/TSBuilder.cs
  src/azure/Model/CodeModelTSa.cs
  src/azure/Templates/AzureServiceClientContextTemplate.cshtml
  src/vanilla/Model/CodeModelTS.cs
  src/vanilla/Templates/ServiceClientContextTemplate.cshtml
  test/azure/generated/AzureCompositeModelClient/azureCompositeModelContext.ts
  test/azure/generated/AzureParameterGrouping/autoRestParameterGroupingTestServiceContext.ts
  test/azure/generated/AzureReport/autoRestReportServiceForAzureContext.ts
  test/azure/generated/AzureResource/autoRestResourceFlatteningTestServiceContext.ts
  test/azure/generated/AzureSpecials/autoRestAzureSpecialParametersTestClientContext.ts
  test/azure/generated/CustomBaseUri/autoRestParameterizedHostTestClientContext.ts
  test/azure/generated/Head/autoRestHeadTestServiceContext.ts
  test/azure/generated/HeadExceptions/autoRestHeadExceptionTestServiceContext.ts
  test/azure/generated/Lro/autoRestLongRunningOperationTestServiceContext.ts
  test/azure/generated/Paging/autoRestPagingTestServiceContext.ts
  test/azure/generated/StorageManagementClient/storageManagementClientContext.ts
  test/azure/generated/SubscriptionIdApiVersion/microsoftAzureTestUrlContext.ts
  test/azuremetadata/generated/Lro/lib/autoRestLongRunningOperationTestServiceContext.ts
  test/multiapi/packages/multiapi-test-2017-10-01/lib/autoRestParameterizedHostTestClientContext.ts
  test/multiapi/packages/multiapi-test-2018-02-01/lib/autoRestParameterizedCustomHostTestClientContext.ts
  test/multiapi/packages/multiapi-test-2018-02-01/package-lock.json
  unittests/DSL/TSBuilderTests.cs
  unittests/vanilla/Model/CodeModelTSTests.cs
Labels: in progress
