Repository Azure/autorest.typescript, pull requests merged in 2018-12, with the labels that each got.

#394 Upgrade all dependencies
  .scripts/dependencies.ts
  package.json
  test/azure/azureCustomBaseUri.ts
  test/azure/azureSpecialProperties.ts
  test/azure/head.ts
  test/azure/lro.ts
  test/azure/paging.ts
  test/azure/parameterGrouping.ts
  test/azure/subscriptionIdApiVersion.ts
  test/vanilla/acceptanceTests.ts
  test/vanilla/complexTypesTests.ts
  test/vanilla/headerTests.ts
  test/vanilla/modelFlattening.ts
  test/vanilla/requiredOptionalTests.ts
  test/vanilla/validationTests.ts
  test/xml/xmlTests.ts
Labels: in progress

#395 Remove preview script and update generated markdown block names
  .scripts/dependencies.ts
  .scripts/preview.ts
  README.md
  package.json
  src/DSL/MarkdownBuilder.cs
  src/azure/Model/CodeModelTSa.cs
  src/vanilla/Model/CodeModelTS.cs
  test/azure/lro.ts
  test/azuremetadata/generated/Lro/README.md
  test/azuremetadata/generated/Lro/package.json
  test/metadata/generated/BodyComplex/README.md
  test/metadata/generated/BodyComplex/package.json
  test/multiapi/packages/multiapi-test-2017-10-01/README.md
  test/multiapi/packages/multiapi-test-2017-10-01/package-lock.json
  test/multiapi/packages/multiapi-test-2017-10-01/package.json
  test/multiapi/packages/multiapi-test-2018-02-01/README.md
  test/multiapi/packages/multiapi-test-2018-02-01/package-lock.json
  test/multiapi/packages/multiapi-test-2018-02-01/package.json
  test/multiapi/packages/multiapi-test/README.md
  test/multiapi/packages/multiapi-test/package-lock.json
  test/multiapi/packages/multiapi-test/package.json
Labels: Planned-Sprint-128, Started-Sprint-127, Unplanned-Sprint-127, in progress

#400 Change default generated package version from 0.1.0 to 1.0.0
  src/vanilla/GeneratorSettingsTS.cs
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#401 Update version to 2.1.1
  package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#405 Create PackageJson builder, add README.md to files to include
  src/DSL/JSBuilder.cs
  src/DSL/JSONBuilder.cs
  src/DSL/JSONObject.cs
  src/DSL/JSObject.cs
  src/azure/Model/CodeModelTSa.cs
  src/vanilla/CodeGeneratorTS.cs
  src/vanilla/Model/CodeModelTS.cs
  src/vanilla/Templates/PackageJson.cshtml
  test/azuremetadata/generated/Lro/package.json
  test/metadata/generated/BodyComplex/package.json
  test/multiapi/packages/multiapi-test-2017-10-01/package.json
  test/multiapi/packages/multiapi-test-2018-02-01/package.json
  test/multiapi/packages/multiapi-test/package.json
  unittests/DSL/JSBuilderTests.cs
  unittests/DSL/JSONObjectTests.cs
Labels: Started-Sprint-128, Unplanned-Sprint-128, in progress

#406 Update version to 2.1.2
  package.json
Labels: Started-Sprint-128, Unplanned-Sprint-128, in progress

#403 Extract dependencies-related scripts to an external package
  .scripts/dependencies.ts
  .scripts/latest.ts
  .scripts/local.ts
  .scripts/repository.ts
  .vscode/launch.json
  package.json
Labels: in progress

#409 Add package.json version check
  .scripts/checkPackageJsonVersion.ts
  azure-pipelines.yml
  package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#410 Add only() check
  .scripts/checkEverything.ts
  .scripts/checkForOnlyCalls.ts
  .scripts/checkForSkipCalls.ts
  .scripts/checkPackageJsonVersion.ts
  .scripts/dependenciesOptions.ts
  .scripts/latest.ts
  .scripts/local.ts
  azure-pipelines.yml
  package.json
  src/azure/Model/CodeModelTSa.cs
  src/vanilla/Model/CodeModelTS.cs
  test/azure/azureSpecialProperties.ts
  test/azure/lro.ts
  test/azure/paging.ts
  test/azure/parameterGrouping.ts
  test/azure/subscriptionIdApiVersion.ts
  test/azuremetadata/generated/Lro/package.json
  test/metadata/generated/BodyComplex/package.json
  test/multiapi/packages/multiapi-test-2017-10-01/package-lock.json
  test/multiapi/packages/multiapi-test-2017-10-01/package.json
  test/multiapi/packages/multiapi-test-2018-02-01/package-lock.json
  test/multiapi/packages/multiapi-test-2018-02-01/package.json
  test/multiapi/packages/multiapi-test/package-lock.json
  test/multiapi/packages/multiapi-test/package.json
  test/vanilla/acceptanceTests.ts
  test/vanilla/complexTypesTests.ts
  test/vanilla/modelFlattening.ts
  test/vanilla/requiredOptionalTests.ts
  test/vanilla/validationTests.ts
  test/xml/xmlTests.ts
Labels: Planned-Sprint-129, Started-Sprint-128, Unplanned-Sprint-128, in progress

#415 Change skip() calls to warning
  .scripts/checkEverything.ts
  .scripts/checkForSkipCalls.ts
  .travis.yml
  package.json
  test/multiapi/package-lock.json
  test/multiapi/package.json
  test/multiapi/packages/multiapi-test-2017-10-01/package-lock.json
  test/multiapi/packages/multiapi-test-2018-02-01/package-lock.json
  test/multiapi/packages/multiapi-test/package-lock.json
Labels: Started-Sprint-129, Unplanned-Sprint-129, in progress
