Repository Azure/autorest.typescript, pull requests merged in 2018-09, with the labels that each got.

#273 Enable strict on scripts, fix resulting issues
  .gulp/dotnet.iced
  .scripts/bundlesize.ts
  .scripts/dependencies.ts
  .scripts/tsconfig.json
  package.json
Labels: Started-Sprint-123, Unplanned-Sprint-123, in progress

#274 Update dependency versions
  README.md
  package.json
  src/azure/Model/CodeModelTSa.cs
  src/vanilla/Model/CodeModelTS.cs
  test/azuremetadata/generated/package.json
  test/metadata/generated/package.json
Labels: Started-Sprint-123, Unplanned-Sprint-123, in progress

#275 Restructure accessing settings within generator
  src/Program.cs
  src/azure/CodeGeneratorTSa.cs
  src/azure/Model/CodeModelTSa.cs
  src/azure/Templates/AzureReadmeTemplate.cshtml
  src/azure/Templates/AzureServiceClientContextTemplate.cshtml
  src/vanilla/CodeGeneratorTS.cs
  src/vanilla/GeneratorSettingsTS.cs
  src/vanilla/Model/CodeModelTS.cs
  src/vanilla/Model/CompositeTypeTS.cs
  src/vanilla/Model/EnumTypeTS.cs
  src/vanilla/Templates/PackageJson.cshtml
  src/vanilla/Templates/ReadmeTemplate.cshtml
  src/vanilla/Templates/ServiceClientContextTemplate.cshtml
  src/vanilla/Templates/TsConfig.cshtml
  src/vanilla/Templates/WebpackConfig.cshtml
  src/vanilla/TransformerTS.cs
  unittests/vanilla/Model/CodeModelTSTests.cs
Labels: Started-Sprint-123, Unplanned-Sprint-123, in progress

#276 Pull in a few more settings from autorest.nodejs
  src/vanilla/CodeGeneratorTS.cs
  src/vanilla/GeneratorSettingsTS.cs
  src/vanilla/Templates/LicenseTemplate.cshtml
Labels: Planned-Sprint-123, Started-Sprint-123, in progress

#277 Metadata and bundle size fixes
  .gulp/gulpfile.iced
  .scripts/bundlesize.ts
  src/azure/CodeGeneratorTSa.cs
  src/vanilla/CodeGeneratorTS.cs
  src/vanilla/Templates/PackageJson.cshtml
  src/vanilla/Templates/TsConfigWebpack.cshtml
  src/vanilla/Templates/WebpackConfig.cshtml
  test/azuremetadata/generated/package.json
  test/azuremetadata/generated/tsconfig.esm.json
  test/azuremetadata/generated/webpack.config.js
  test/metadata/generated/package.json
  test/metadata/generated/tsconfig.esm.json
  test/metadata/generated/webpack.config.js
  test/multiapi/generated/package.json
  test/multiapi/generated/webpack.config.js
Labels: Started-Sprint-123, Unplanned-Sprint-123, in progress

#267 Automatically rename conflicting options properties
  .gulp/regeneration.iced
  src/vanilla/TransformerTS.cs
  test/rename-parameter/generated/lib/autoRestRenameParameterTestService.ts
  test/rename-parameter/generated/lib/autoRestRenameParameterTestServiceContext.ts
  test/rename-parameter/generated/lib/models/index.ts
  test/rename-parameter/generated/lib/models/mappers.ts
  test/rename-parameter/generated/lib/models/parameters.ts
  test/rename-parameter/rename-parameter.json
Labels: Started-Sprint-123, in progress

#280 Additional properties
  .gulp/regeneration.iced
  README.md
  package.json
  src/vanilla/ClientModelExtensions.cs
  src/vanilla/Model/CodeModelTS.cs
  src/vanilla/Model/CompositeTypeTS.cs
  src/vanilla/Templates/ModelTemplate.cshtml
  src/vanilla/TransformerTS.cs
  test/azure/generated/AzureCompositeModelClient/models/index.ts
  test/azure/generated/AzureCompositeModelClient/models/mappers.ts
  test/azuremetadata/generated/Lro/.npmignore
  test/azuremetadata/generated/Lro/README.md
  test/metadata/generated/BodyComplex/.npmignore
  test/metadata/generated/BodyComplex/README.md
  test/metadata/generated/BodyComplex/lib/models/index.ts
  test/metadata/generated/BodyComplex/lib/models/mappers.ts
  test/metadata/generated/BodyComplex/package.json
  test/startServer.ts
  test/vanilla/additionalPropertiesTests.ts
  test/vanilla/generated/AdditionalProperties/additionalPropertiesClient.ts
  test/vanilla/generated/AdditionalProperties/additionalPropertiesClientContext.ts
  test/vanilla/generated/AdditionalProperties/models/index.ts
  test/vanilla/generated/AdditionalProperties/models/mappers.ts
  test/vanilla/generated/AdditionalProperties/models/petsMappers.ts
  test/vanilla/generated/AdditionalProperties/operations/index.ts
  test/vanilla/generated/AdditionalProperties/operations/pets.ts
  test/vanilla/generated/BodyComplex/models/index.ts
  test/vanilla/generated/BodyComplex/models/mappers.ts
  test/vanilla/zz_coverage.ts
Labels: in progress

#282 Fix polymorphism
  src/vanilla/ClientModelExtensions.cs
  test/azure/generated/AzureCompositeModelClient/models/mappers.ts
  test/metadata/generated/BodyComplex/lib/models/mappers.ts
  test/vanilla/acceptanceTests.ts
  test/vanilla/complexTypesTests.ts
  test/vanilla/generated/BodyComplex/models/mappers.ts
Labels: in progress

#288 Fix scripts for metadata, azuremetadata, and multiapi tests
  .scripts/repository.ts
  README.md
  package.json
  src/azure/Model/CodeModelTSa.cs
  src/vanilla/Model/CodeModelTS.cs
  test/azuremetadata/generated/Lro/package.json
  test/metadata/generated/BodyComplex/package.json
  test/multiapi/generated/package.json
Labels: Started-Sprint-124, Unplanned-Sprint-124, in progress

#289 Automatically determine package.json version from existing package.js…
  src/Program.cs
  src/vanilla/GeneratorSettingsTS.cs
  test/multiapi/generated/2017-10-01/lib/autoRestParameterizedHostTestClientContext.ts
  test/multiapi/generated/2018-02-01/lib/autoRestParameterizedCustomHostTestClientContext.ts
  test/multiapi/generated/package.json
Labels: Planned-Sprint-124, Started-Sprint-124, in progress

#292 Check the value of LRO extension instead of just its existence
  src/azure/Model/MethodTSa.cs
Labels: Started-Sprint-124, Unplanned-Sprint-124, in progress

#293 Change generated homepage urls based on azure-sdk-for-js folder structure
  src/vanilla/Model/CodeModelTS.cs
  unittests/vanilla/Model/CodeModelTSTests.cs
Labels: Started-Sprint-124, Unplanned-Sprint-124, in progress

#315 Update README.md
  README.md
Labels: in progress

#317 Update MethodTS.HttpResponseName to look for duplicated ModelType names
  src/azure/Templates/AzureModelIndexTemplate.cshtml
  src/vanilla/Model/CodeModelTS.cs
  src/vanilla/Model/MethodTS.cs
  src/vanilla/Templates/ModelIndexTemplate.cshtml
  test/azure/generated/Lro/models/index.ts
  test/azure/generated/Paging/models/index.ts
  test/azuremetadata/generated/Lro/lib/models/index.ts
  test/date-time-as-string/generated/BodyDateTime/models/index.ts
  test/vanilla/generated/BodyDateTime/models/index.ts
  test/vanilla/generated/Http/models/index.ts
Labels: in progress
