Repository Azure/autorest.typescript, pull requests merged in 2018-08, with the labels that each got.

#238 Fix tests
  package.json
  test/azure/head.ts
  test/azure/lro.ts
  test/azure/paging.ts
  test/vanilla/acceptanceTests.ts
Labels: in progress

#242 Fix bug related to null serializedName
  src/vanilla/ClientModelExtensions.cs
Labels: in progress

#244 Fix should() regression in browser tests
  README.md
  package.json
  src/azure/Model/CodeModelTSa.cs
  src/vanilla/Model/CodeModelTS.cs
  test/azuremetadata/generated/package.json
  test/metadata/generated/package.json
  test/xml/xmlTests.ts
Labels: in progress

#247 Disable client side validation
  .gulp/regeneration.iced
  README.md
  package.json
  src/Program.cs
  src/azure/Model/CodeModelTSa.cs
  src/vanilla/ClientModelExtensions.cs
  src/vanilla/Model/CodeModelTS.cs
  test/azuremetadata/generated/package.json
  test/metadata/generated/package.json
  test/no-client-validation/generated/Validation/autoRestValidationTest.ts
  test/no-client-validation/generated/Validation/autoRestValidationTestContext.ts
  test/no-client-validation/generated/Validation/models/index.ts
  test/no-client-validation/generated/Validation/models/mappers.ts
  test/no-client-validation/generated/Validation/models/parameters.ts
  test/no-client-validation/noClientValidationTests.ts
  test/vanilla/acceptanceTests.ts
Labels: in progress

#249 Add clean step to metadata test
  .gulp/gulpfile.iced
Labels: in progress

#250 Publish release builds
  package.json
Labels: in progress

#254 Various improvements to our script infrastructure
  .gulp/gulpfile.iced
  .scripts/bundlesize.ts
  .scripts/dependencies.js
  .scripts/dependencies.ts
  .scripts/latest.js
  .scripts/latest.ts
  .scripts/local.js
  .scripts/local.ts
  .scripts/preview.js
  .scripts/preview.ts
  .scripts/repository.ts
  README.md
  package.json
  src/vanilla/Model/CodeModelTS.cs
  test/metadata/generated/package.json
Labels: Started-Sprint-123, Unplanned-Sprint-123, in progress

#257 Skip some tests in other browsers
  test/vanilla/acceptanceTests.ts
  test/vanilla/validationTests.ts
Labels: in progress

#258 Date as string
  .gulp/regeneration.iced
  README.md
  package.json
  src/Program.cs
  src/azure/CodeGeneratorTSa.cs
  src/azure/Model/CodeModelTSa.cs
  src/vanilla/CodeGeneratorTS.cs
  src/vanilla/GeneratorSettingsTS.cs
  src/vanilla/Model/CodeModelTS.cs
  src/vanilla/TransformerTS.cs
  test/azuremetadata/generated/package.json
  test/date-as-string/dateAsStringTests.ts
  test/date-as-string/generated/BodyDate/autoRestDateTestService.ts
  test/date-as-string/generated/BodyDate/autoRestDateTestServiceContext.ts
  test/date-as-string/generated/BodyDate/models/dateModelMappers.ts
  test/date-as-string/generated/BodyDate/models/index.ts
  test/date-as-string/generated/BodyDate/models/mappers.ts
  test/date-as-string/generated/BodyDate/operations/dateModel.ts
  test/date-as-string/generated/BodyDate/operations/index.ts
  test/date-as-string/generated/BodyDateTime/autoRestDateTimeTestService.ts
  test/date-as-string/generated/BodyDateTime/autoRestDateTimeTestServiceContext.ts
  test/date-as-string/generated/BodyDateTime/models/datetimeMappers.ts
  test/date-as-string/generated/BodyDateTime/models/index.ts
  test/date-as-string/generated/BodyDateTime/models/mappers.ts
  test/date-as-string/generated/BodyDateTime/operations/datetime.ts
  test/date-as-string/generated/BodyDateTime/operations/index.ts
  test/date-as-string/generated/BodyDateTimeRfc1123/autoRestRFC1123DateTimeTestService.ts
  test/date-as-string/generated/BodyDateTimeRfc1123/autoRestRFC1123DateTimeTestServiceContext.ts
  test/date-as-string/generated/BodyDateTimeRfc1123/models/datetimerfc1123Mappers.ts
  test/date-as-string/generated/BodyDateTimeRfc1123/models/index.ts
  test/date-as-string/generated/BodyDateTimeRfc1123/models/mappers.ts
  test/date-as-string/generated/BodyDateTimeRfc1123/operations/datetimerfc1123.ts
  test/date-as-string/generated/BodyDateTimeRfc1123/operations/index.ts
  test/metadata/generated/package.json
Labels: in progress

#255 Update LRO methods
  .scripts/dependencies.ts
  .vscode/launch.json
  README.md
  package.json
  src/azure/Model/CodeModelTSa.cs
  src/azure/Model/MethodTSa.cs
  src/azure/Templates/AzureMethodGroupTemplate.cshtml
  src/azure/Templates/AzureMethodTemplate.cshtml
  src/azure/Templates/AzureServiceClientTemplate.cshtml
  src/vanilla/Model/CodeModelTS.cs
  src/vanilla/Model/MethodGroupTS.cs
  src/vanilla/Model/MethodTS.cs
  src/vanilla/Templates/MethodGroupTemplate.cshtml
  src/vanilla/Templates/ServiceClientTemplate.cshtml
  test/azure/generated/Lro/operations/lRORetrys.ts
  test/azure/generated/Lro/operations/lROSADs.ts
  test/azure/generated/Lro/operations/lROs.ts
  test/azure/generated/Lro/operations/lROsCustomHeader.ts
  test/azure/generated/Paging/operations/paging.ts
  test/azure/generated/StorageManagementClient/operations/storageAccounts.ts
  test/azure/lro.ts
  test/azuremetadata/generated/lib/operations/lRORetrys.ts
  test/azuremetadata/generated/lib/operations/lROSADs.ts
  test/azuremetadata/generated/lib/operations/lROs.ts
  test/azuremetadata/generated/lib/operations/lROsCustomHeader.ts
  test/azuremetadata/generated/package.json
  test/metadata/generated/package.json
Labels: Planned-Sprint-122, Planned-Sprint-123, Started-Sprint-122, in progress

#259 Fix bundle size script
  .scripts/bundlesize.ts
Labels: in progress

#260 Add a build step that checks our scripts
  .gulp/dotnet.iced
  .gulp/gulpfile.iced
  .scripts/tsconfig.json
Labels: Started-Sprint-123, Unplanned-Sprint-123, in progress

#264 Date time as string
  .gulp/regeneration.iced
  README.md
  package.json
  src/Program.cs
  src/vanilla/GeneratorSettingsTS.cs
  src/vanilla/Model/CodeModelTS.cs
  src/vanilla/TransformerTS.cs
  test/date-as-string/dateAsStringTests.ts
  test/date-time-as-string/dateAsStringTests.ts
  test/date-time-as-string/generated/BodyDate/autoRestDateTestService.ts
  test/date-time-as-string/generated/BodyDate/autoRestDateTestServiceContext.ts
  test/date-time-as-string/generated/BodyDate/models/dateModelMappers.ts
  test/date-time-as-string/generated/BodyDate/models/index.ts
  test/date-time-as-string/generated/BodyDate/models/mappers.ts
  test/date-time-as-string/generated/BodyDate/operations/dateModel.ts
  test/date-time-as-string/generated/BodyDate/operations/index.ts
  test/date-time-as-string/generated/BodyDateTime/autoRestDateTimeTestService.ts
  test/date-time-as-string/generated/BodyDateTime/autoRestDateTimeTestServiceContext.ts
  test/date-time-as-string/generated/BodyDateTime/models/datetimeMappers.ts
  test/date-time-as-string/generated/BodyDateTime/models/index.ts
  test/date-time-as-string/generated/BodyDateTime/models/mappers.ts
  test/date-time-as-string/generated/BodyDateTime/operations/datetime.ts
  test/date-time-as-string/generated/BodyDateTime/operations/index.ts
  test/date-time-as-string/generated/BodyDateTimeRfc1123/autoRestRFC1123DateTimeTestService.ts
  test/date-time-as-string/generated/BodyDateTimeRfc1123/autoRestRFC1123DateTimeTestServiceContext.ts
  test/date-time-as-string/generated/BodyDateTimeRfc1123/models/datetimerfc1123Mappers.ts
  test/date-time-as-string/generated/BodyDateTimeRfc1123/models/index.ts
  test/date-time-as-string/generated/BodyDateTimeRfc1123/models/mappers.ts
  test/date-time-as-string/generated/BodyDateTimeRfc1123/operations/datetimerfc1123.ts
  test/date-time-as-string/generated/BodyDateTimeRfc1123/operations/index.ts
Labels: in progress

#266 Readonly doc
  src/DSL/TSObjectType.cs
  src/vanilla/Model/CompositeTypeTS.cs
  src/vanilla/Model/MethodTS.cs
  src/vanilla/TransformerTS.cs
  test/azure/generated/AzureCompositeModelClient/models/index.ts
  test/azure/generated/AzureResource/models/index.ts
  test/azure/generated/AzureSpecials/models/index.ts
  test/azure/generated/Lro/models/index.ts
  test/azure/generated/Paging/models/index.ts
  test/azure/generated/StorageManagementClient/models/index.ts
  test/azure/generated/SubscriptionIdApiVersion/models/index.ts
  test/azuremetadata/generated/lib/models/index.ts
  test/enumunion/generated/BodyString/models/index.ts
  test/metadata/generated/lib/models/index.ts
  test/no-client-validation/generated/Validation/models/index.ts
  test/vanilla/generated/BodyComplex/models/index.ts
  test/vanilla/generated/BodyString/models/index.ts
  test/vanilla/generated/ComplexModelClient/models/index.ts
  test/vanilla/generated/Header/models/index.ts
  test/vanilla/generated/Http/models/index.ts
  test/vanilla/generated/ModelFlattening/models/index.ts
  test/vanilla/generated/RequiredOptional/models/index.ts
  test/vanilla/generated/Validation/models/index.ts
  test/xml/generated/Xml/models/index.ts
Labels: in progress

#268 No options mappers
  src/azure/Templates/AzureMapperIndexTemplate.cshtml
  src/vanilla/Model/CodeModelTS.cs
  src/vanilla/Templates/MapperIndexTemplate.cshtml
  test/azure/generated/AzureCompositeModelClient/models/mappers.ts
  test/azure/generated/AzureParameterGrouping/models/mappers.ts
  test/azure/generated/AzureReport/models/mappers.ts
  test/azure/generated/AzureResource/models/mappers.ts
  test/azure/generated/AzureSpecials/models/mappers.ts
  test/azure/generated/Lro/models/mappers.ts
  test/azure/generated/Paging/models/mappers.ts
  test/azure/generated/StorageManagementClient/models/mappers.ts
  test/azuremetadata/generated/lib/models/mappers.ts
  test/enumunion/generated/BodyString/models/mappers.ts
  test/metadata/generated/lib/models/mappers.ts
  test/no-client-validation/generated/Validation/models/mappers.ts
  test/vanilla/generated/BodyComplex/models/mappers.ts
  test/vanilla/generated/BodyString/models/mappers.ts
  test/vanilla/generated/ComplexModelClient/models/mappers.ts
  test/vanilla/generated/CustomBaseUriMoreOptions/models/mappers.ts
  test/vanilla/generated/Header/models/mappers.ts
  test/vanilla/generated/Http/models/mappers.ts
  test/vanilla/generated/ModelFlattening/models/mappers.ts
  test/vanilla/generated/Report/models/mappers.ts
  test/vanilla/generated/RequiredOptional/models/mappers.ts
  test/vanilla/generated/Url/models/mappers.ts
  test/vanilla/generated/UrlMultiCollectionFormat/models/mappers.ts
  test/vanilla/generated/Validation/models/mappers.ts
Labels: in progress

#270 Paging fix
  package.json
  src/vanilla/Model/MethodTS.cs
  test/azure/generated/AzureCompositeModelClient/models/index.ts
  test/azure/generated/AzureResource/models/index.ts
  test/azure/generated/AzureSpecials/models/index.ts
  test/azure/generated/Lro/models/index.ts
  test/azure/generated/Paging/models/index.ts
  test/azure/generated/StorageManagementClient/models/index.ts
  test/azure/generated/SubscriptionIdApiVersion/models/index.ts
  test/azure/paging.ts
  test/azuremetadata/generated/lib/models/index.ts
  test/enumunion/generated/BodyString/models/index.ts
  test/metadata/generated/lib/models/index.ts
  test/no-client-validation/generated/Validation/models/index.ts
  test/vanilla/acceptanceTests.ts
  test/vanilla/generated/BodyComplex/models/index.ts
  test/vanilla/generated/BodyString/models/index.ts
  test/vanilla/generated/ComplexModelClient/models/index.ts
  test/vanilla/generated/Header/models/index.ts
  test/vanilla/generated/Http/models/index.ts
  test/vanilla/generated/ModelFlattening/models/index.ts
  test/vanilla/generated/RequiredOptional/models/index.ts
  test/vanilla/generated/Validation/models/index.ts
  test/xml/generated/Xml/models/index.ts
Labels: in progress

#271 Optional headers
  .gulp/regeneration.iced
  README.md
  src/Program.cs
  src/vanilla/GeneratorSettingsTS.cs
  src/vanilla/Model/CodeModelTS.cs
  src/vanilla/Model/CompositeTypeTS.cs
  test/optional-response-headers/generated/Header/autoRestSwaggerBATHeaderService.ts
  test/optional-response-headers/generated/Header/autoRestSwaggerBATHeaderServiceContext.ts
  test/optional-response-headers/generated/Header/models/headerMappers.ts
  test/optional-response-headers/generated/Header/models/index.ts
  test/optional-response-headers/generated/Header/models/mappers.ts
  test/optional-response-headers/generated/Header/models/parameters.ts
  test/optional-response-headers/generated/Header/operations/header.ts
  test/optional-response-headers/generated/Header/operations/index.ts
Labels: in progress
