Repository Azure/autorest.typescript, pull requests merged in 2019-01, with the labels that each got.

#418 Update azure-js-dev-tools version and add repo folder to packageFolders
  .scripts/dependenciesOptions.ts
  package.json
Labels: Started-Sprint-129, Unplanned-Sprint-129, in progress

#420 Add case-insensitive checks for MethodGroupTS model sorting
  package.json
  src/vanilla/Model/MethodGroupTS.cs
  test/azure/generated/AzureCompositeModelClient/models/primitiveMappers.ts
  test/azure/generated/AzureSpecials/models/headerMappers.ts
  test/azure/generated/Lro/models/lROsMappers.ts
  test/azuremetadata/generated/Lro/lib/models/lROsMappers.ts
  test/metadata/generated/BodyComplex/lib/models/primitiveMappers.ts
  test/skip-subtypes/generated/BodyComplex/lib/models/primitiveMappers.ts
  test/vanilla/generated/BodyComplex/models/primitiveMappers.ts
Labels: Started-Sprint-129, Unplanned-Sprint-129, in progress

#422 Fix failing tests
  package.json
  src/azure/Model/CodeModelTSa.cs
  test/azure/azureSpecialProperties.ts
  test/azure/lro.ts
  test/azure/paging.ts
  test/azure/parameterGrouping.ts
  test/azuremetadata/generated/Lro/package.json
  test/multiapi/packages/multiapi-test-2017-10-01/package-lock.json
  test/multiapi/packages/multiapi-test-2017-10-01/package.json
  test/multiapi/packages/multiapi-test-2018-02-01/package-lock.json
  test/multiapi/packages/multiapi-test-2018-02-01/package.json
  test/multiapi/packages/multiapi-test/package-lock.json
  test/multiapi/packages/multiapi-test/package.json
  test/vanilla/requiredOptionalTests.ts
Labels: Planned-Sprint-129, in progress

#425 Add generating "autoPublish" package.json property
  package.json
  src/vanilla/GeneratorSettingsTS.cs
  src/vanilla/Model/CodeModelTS.cs
Labels: in progress

#428 Update ms-rest-js and ms-rest-azure-js packages
  README.md
  package.json
  src/azure/Model/CodeModelTSa.cs
  src/vanilla/CodeGeneratorTS.cs
  src/vanilla/Model/CodeModelTS.cs
  test/azuremetadata/generated/Lro/package.json
  test/metadata/generated/BodyComplex/package.json
  test/multiapi/packages/multiapi-test-2017-10-01/package-lock.json
  test/multiapi/packages/multiapi-test-2017-10-01/package.json
  test/multiapi/packages/multiapi-test-2018-02-01/package-lock.json
  test/multiapi/packages/multiapi-test-2018-02-01/package.json
  test/multiapi/packages/multiapi-test/package-lock.json
  test/multiapi/packages/multiapi-test/package.json
  test/skip-subtypes/generated/BodyComplex/package.json
Labels: in progress
